### ISSUE TITLE
Daily Note command broken after updating to 0.21.2

### ISSUE THREAD

**Issue by quantum-cowboy** [foambubble/foam#1188]
### Describe the bug

Open Today's Note and Open Daily Note commands are not functioning. After executing the command, nothing happens. I reverted to the previous update and the commands work again. 

### Steps to Reproduce the Bug or Issue

1. Update to v0.21.2
2. Open command pallet `Ctrl+Shift+P`
3. Execute `Foam: Open Today's Note` or `Foam: Open Daily Note`

### Expected behavior

As a user, I expect for today's daily note to be opened, or if there is no daily note I expect for the command to create a daily note for today. This issue occurs whether there is a daily note created for the selected day or not. 

### Operating System Version

Windows 11

### Visual Studio Code Version

1.77.3

**Comment by riccardoferretti** [comment]
Thanks for reporting the issue, it was due to some changes in the way relative paths are resolved when creating notes from templates.
I pushed a fix and released 0.21.3 - check and let me know if everything is in order, thanks!

**Comment by joar28** [comment]
I still have a issue with daily notes where it behaves as explained here, in the debug console output it gives me this message: 

```
  ERR expected hexadecimal character at line 3, column 18:
      filepath: "C:\Users\UserNameFolder\Source\Repos\ ... 
                     ^: Error: expected hexadecimal character at line 3, column 18:
      filepath: "C:\Users\UserNameFolder\Source\Repos\ ... 
                     ^
	at m.h (c:\Users\UserNameFolder\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:126151)
```

I am running the `v0.21.3` now, it worked before this.
Is this the same issue, or something else?

**Comment by riccardoferretti** [comment]
mmm.. I can't reproduce it, so I wonder also given the error message shared whether there is something related to Windows. What are your settings and/or what does your `daily-note.md` template look like?

**Comment by hyogoa2c** [comment]
I experienced same behavior with `v0.21.3` and `v0.21.2` with Windows 10 , VSCode 1.77.3. 
New daily note was note created and prev daily note opend.
with older version `v0.21.1` (down graded) with  Windows 10 and VSCode, new note cration and opning prev note works as expected

**Comment by riccardoferretti** [comment]
@hyogoa2c Do you have a `daily-note.md` template? If so what is the `filepath` property like? If not, do you have custom settings for daily note creation?

@joar28 do you have the full stack trace?

**Comment by hyogoa2c** [comment]
@riccardoferretti I do not have `daily-note.md` template. `filepath` is configured as `"foam.openDailyNote.directory": "journal",`.

**Comment by joar28** [comment]
Hi @riccardoferretti, I do not have the full stack trace, seems it is concatenated before I'm able to fetch it (if you have a fast way to make it verbose enough, I can add it here). 

I am on windows 11 if that is relevant. 

The only configs I have defined for `foam.openDailyNote.*` are these 

```
  "foam.openDailyNote.directory": "journal",
  "foam.openDailyNote.titleFormat": "fullDate",
```

I did not know about the magic `daily-note.md` template, so I did not have it (I wanted this exact template like this, but not find it in any documentation), so I added the daily-note.md template now, and then it starter working again. 

Is there some "hidden" or auto-generated `daily-note.md` that is used when the template file does not exist? And could that have any characters that creates this error?

**Comment by RoBaaaT** [comment]
Hi, I am experiencing the same issue, also with `v0.21.3` on Windows 11, VSCode 1.77.3.

I have the following configuration options set for foam:
```
    "foam.openDailyNote.directory": "daily-notes",
    "foam.openDailyNote.titleFormat": "dddd, yyyy-mm-dd \"[[daily-notes]]\"",
```

In the Extension Host output, I get the following stacktrace when running the "Open Today's Note" command:
```
2023-04-14 10:12:02.481 [error] YAMLException: expected hexadecimal character at line 3, column 18:
      filepath: "C:\Users\XYZ123\log\daily-notes\20 ... 
                     ^
	at a0 (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:31:792)
	at X (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:31:892)
	at ON (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:32:1940)
	at Yi (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4445)
	at MN (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:1769)
	at Yi (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4398)
	at MN (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:1769)
	at Yi (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4398)
	at qN (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:6530)
	at u0 (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:258)
	at c0 (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:469)
	at Object.WN [as safeLoad] (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:736)
	at J0.exports (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:58:1105)
	at qM (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:59:422)
	at wt (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:58:1427)
	at pf (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:253:608)
	at s2 (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:275:290)
	at async Object.createFromTemplate (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:275:2616)
	at async Af (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:290:10)
	at async ns (c:\Users\XYZ123\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:285:1293)
	at async m.h (c:\Users\XYZ123\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125789) foam-vscode.open-daily-note {"value":"foam.foam-vscode","c":"foam.foam-vscode"}
```

Maybe this helps? I also do not have a `daily-note.md` template file, just the configuration settings mentioned above.

Thanks for the great work on the extension!

**Comment by jesusnunezpro** [comment]
Got the same error, backslashes are interpreted like escape sequences in YAML... but I can't tell if it's an actual YAML file somewhere or something generated dynamically. Is there any workaround?

```log
2023-04-14 11:10:08.973 [error] YAMLException: unknown escape sequence at line 3, column 17:
      filepath: "C:\git-projects\notes\journal\2023- ... 
                    ^
	at a0 (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:31:792)
	at X (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:31:892)
	at ON (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:32:2012)
	at Yi (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4445)
	at MN (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:1769)
	at Yi (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4398)
	at MN (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:1769)
	at Yi (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:4398)
	at qN (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:38:6530)
	at u0 (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:258)
	at c0 (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:469)
	at Object.WN [as safeLoad] (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:39:736)
	at J0.exports (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:58:1105)
	at qM (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:59:422)
	at wt (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:58:1427)
	at pf (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:253:608)
	at s2 (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:275:290)
	at async Object.createFromTemplate (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:275:2616)
	at async Af (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:290:10)
	at async ns (c:\Users\jnunez\.vscode\extensions\foam.foam-vscode-0.21.3\out\extension.js:285:1293)
	at async m.h (c:\Users\jnunez\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125789) foam-vscode.open-daily-note {"value":"foam.foam-vscode","c":"foam.foam-vscode"}
```

**Comment by riccardoferretti** [comment]
Ok, we are now (0.21.4) escaping the path, it should address the issue - can you please confirm?

**Comment by frigolay** [comment]
Works for me again! I used today and Sunday.
