### ISSUE TITLE
Graph nodes are not properly highlighted on light themes 

### ISSUE THREAD

**Issue by riccardoferretti** [foambubble/foam#455]
- Foam version: 0.8.0
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes 

**Summary**
When a node is selected in the graph, the other nodes don't become less prominent.

I believe the reason is that when we get the style for the nodes that are "lessened", we darken the color.
That works on a dark background, but doesn't on a light one.
The graph needs to know what type of theme it's on, and needs to darken or lighten the base color as a consequence.

**Steps to reproduce**
1. Select a light theme
2. open the graph
3. highlight a node

You will see that the other nodes are still in their "full color".
![image](https://user-images.githubusercontent.com/457005/105512777-d536f100-5cd1-11eb-84d3-a6b18b5f8659.png)

![image](https://user-images.githubusercontent.com/457005/105512848-e8e25780-5cd1-11eb-816a-3818a0978d4a.png)

**Comment by riccardoferretti** [comment]
this has been fixed in #479

**Comment by AliArdaOrhan** [comment]
This still not working in 0.10.3 despite there isn't any problem with 0.9.x

**Comment by riccardoferretti** [comment]
@AliArdaOrhan what problem are you seeing? can you add a screenshot?

**Comment by AliArdaOrhan** [comment]
All nodes seems highlighted in new versions. That makes it really hard to navigate. First one is from 0.9.1 version. Second ss is from 0.10.3 version. At second SS you can see that **Portfolio Management** node is selected, however all the other as well are looked highlighted.

![image](https://user-images.githubusercontent.com/8167817/109507405-c05b3380-7aaf-11eb-8956-664554133d37.png)

![image](https://user-images.githubusercontent.com/8167817/109507659-02847500-7ab0-11eb-99be-bee41416d783.png)

**Comment by riccardoferretti** [comment]
Can you please create a new issue to track this @AliArdaOrhan ?
