### ISSUE TITLE
Foam graph fails to render

### ISSUE THREAD

**Issue by peeksake** [foambubble/foam#495]
- Foam version: 0.10.0
- Platform: Linux hosting the notebook

**Summary**
Fails to render graph in both my notebooks.
```
[info - 1:01:32 PM] Loaded 131 notes
[error - 1:01:34 PM] An error occurred in the graph view
{
  "message": "Uncaught TypeError: Cannot read property 'id' of undefined",
  "filename": "vscode-webview-resource://df20ba54-b5f5-4f38-85ae-d5f033ef7928/file///home/admin/.vscode-server/extensions/foam.foam-vscode-0.10.0/static/graphs/default/graph.js",
  "lineno": 228,
  "colno": 24,
  "error": {}
} 
```

**Comment by ipedrazas** [comment]
I have the same issue with `0.10.0`. My Foam version was updated a couple of days ago. Just downgraded it to `0.9.1` and the graph is back (it took a few attempts to reload the new js, but it's working).

My `Code -OSS` details:

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T21:13:58.622Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.15-arch1-1
```

**Comment by riccardoferretti** [comment]
thanks for reporting the issue, do you have a reproducible example to help us debug it?

**Comment by cureau** [comment]
I don't have a shareable repo, but thought I'd chime in, because I'm on Mac Mohave (10.14.5) and not Linux, as the two commenters above.

The issue appeared in `0.10.0` and like @ipedrazas, a downgrade to `0.9.1` fixed it for me. (VS Code Version 1.53.2)

**Comment by ingalless** [comment]
@riccardoferretti Annoyingly my notes were failing - then they fixed after I ran a debugging session!
Would a reinstall of the extension kick anything into action do you think?

**Comment by ipedrazas** [comment]
I've just done a fresh install of `code` & `foam` in an Ubuntu VM and the graph is displayed.

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-38-generic snap
```

**Comment by peeksake** [comment]
downgrades seem to work as noted above. reinstalling the extension doesn't seem to work. 

I was able to replicate the issue by cloning the foam bubble repo onto my ubuntu 18.04 machine/windows and deleting the docs folder this works both remote and local. This behavior stays for the duration of the vs code lifecycle and works when it restarts however neither of my other workbooks follow the same behavior.  

Not sure how helpful that is. Might be able to dig in later and provide some more verbose outputs however both of my notebooks are unsharable. 


code -v
```
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```

**Comment by ipedrazas** [comment]
Found the issue! It is related to the way the `link references` work.

I've installed a new code insiders, new foam extension, new repo, everything works (this behaviour matches with my ubuntu test).

I've opened my foam directory with insiders and the issue happened again. Removed all the files and started adding one by one until the graph issue happened. Opened that file and there were errors like this:

```
[warn - 18:58:01] Link file:///home/user/foam/todo.md in file:///home/user/foam/getting-started.md is not valid.
```

So, previously, the `link references` would generate something like this when adding these links: `[[reading-dashboard]] [[book]] [[maths]] [[formal methods]]`

```
[//begin]: # "Autogenerated link references for markdown compatibility"
[reading-dashboard]: ../books/reading-dashboard.md "Reading Dashboard"
[book]: ../books/book.md "book"
[//end]: # "Autogenerated link references"
```
But now, the `link references` block is not there (clicking on the links takes you to the right file) And if you check the backlinks, you can see that `reading-dashboard.md` has a ref to the file where the link `[[reading-dashboard]]` defined.

So, the "only" thing that you need to do to "fix" this graph issue is to re-open all the files with broken ref links and let foam sort them out.

Not sure if there's a way of cleaning up or re-indexing the `link references`

**Comment by ingalless** [comment]
@ipedrazas To add to this - I ran the "Foam: Run Janitor (Experimental)" command (which should re-index link refs) _before_ doing my debug session. 
It could be that doing this wasn't enough to trigger the graph itself to reindex, but once I'd restarted the VS Code (following my debug session) and the graph reindexed that my refs were sorted?

**Comment by riccardoferretti** [comment]
this has now been fixed with the Foam 0.10.1 - can you please validate?

**Comment by technikhil314** [comment]
I still face the same issue. 

Here are my system details and the log in vscode dev tools

foam.foam-vscode@0.10.2
vscode 1.53.2
vscode commit HEAD @ 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Macos big sur 11.2


﻿```
workbench.desktop.main.js:618   ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at /Users/myuser/.vscode/extensions/foam.foam-vscode-0.10.2/out/features/dataviz.js:63:27
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:43363
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at p.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:129395)
    at p.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:127566)
    at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:10276)
    at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9968)
    at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8638)
    at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:7440)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:5568
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:29104
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:20765)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:17659
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at u.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12880)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12228
    at Socket.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:12375)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
﻿```

**Comment by riccardoferretti** [comment]
@technikhil314 I don't recognize that error, but we just released 0.10.3, which solves a different issue from the one in 0.10.2 that manifested in the same way in the graph (so maybe you were actually hitting that one). 
Can you try with 0.10.3 ?

**Comment by technikhil314** [comment]
@riccardoferretti No worries. I guess it was something the way I had my markdown file linked. I simply created new repo copied all my files to it and it worked. Not sure what was the issue
