### ISSUE TITLE
[[link-formatting-and-autocompletion]] is not a linking to a page in the docs

### ISSUE THREAD

**Issue by LePeti** [foambubble/foam#711]
Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: **No**

**Summary**
- When reading the documentation on https://foambubble.github.io/foam, I saw that the [[link-formatting-and-autocompletion]] link wasn't an actual link.
- Its corresponding link reference definition was missing from the bottom.
- I tried to put it back but didn't find reference to such a file in the docs folder.

**Steps to reproduce**
Visit these pages and search for 'link-formatting-and-autocompletion'
1. [Wiki Links](https://github.com/foambubble/foam/blob/6b3eef43a8ec8980d94696afcce4ab7ecbc51f3d/docs/index.md) 
2. [FAQ](https://github.com/foambubble/foam/blob/d4adce673097f222cf90a7bea92c2ea90741f1c9/docs/frequently-asked-questions.md)

**Comment by riccardoferretti** [comment]
this has been fixed some time ago, closing

**Comment by t2hv33** [comment]
@riccardoferretti Not fixing yet, I still see this issue

<img width="608" alt="KW 2022-06-19 at 17 23 34@2x" src="https://user-images.githubusercontent.com/7752328/174476460-d6f6480c-da28-4f87-ae5a-a67076f314b3.png">
https://github.com/foambubble/foam/blob/master/docs/wikilinks.md

**Comment by riccardoferretti** [comment]
Fixed now, thanks for reporting
