### ISSUE TITLE
Link to a section does not reflect in linked note's backlinks

### ISSUE THREAD

**Issue by veesar** [foambubble/foam#895]
It would be good to see the notes linking to current note in the Backlinks even if the link is to a section.

The scenario:
1. Link in note-a to `[[note-b#section-1]]`
2. Link in note-c to `[[note-b]]`
3. note-b's Backlinks panel shows note-c but not note-a

I'm not sure if this is expected behavior? If it is, it would be good to have this feature so that it provides better Backlinks context.

Foam version: 0.17.2

**Comment by riccardoferretti** [comment]
The expected behavior would be for a link to a section to show up in the backlinks for the note, so this sounds like a bug to me

**Comment by riccardoferretti** [comment]
Fixed in 0.17.7

**Comment by shelper** [comment]
this is still buggy?
i am on 0.25.7 and this backlink for sections seems not working again. 
i am on vscode 1.86.1, windows 10,

**Comment by riccardoferretti** [comment]
Nope, this was fixed. If there is a regression can you please file a bug with steps/setup to reproduce it? thanks!
